apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: train-als-model-{{ ds_nodash }}
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "DOCKERHUB_USERNAME_PLACEHOLDER/amazon-recommender-spark:latest"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/src/spark/train_model.py"
  sparkVersion: "3.5.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1024m"
    labels:
      version: 3.5.1
    serviceAccount: spark
    env:
      - name: S3_DATA_LAKE_BUCKET
        value: "{{ var.value.S3_DATA_LAKE_BUCKET }}"
      - name: MLFLOW_TRACKING_URI
        value: "{{ var.value.MLFLOW_TRACKING_URI }}"
  executor:
    cores: 2
    instances: 2
    memory: "2048m"
    labels:
      version: 3.5.1
    env:
      - name: S3_DATA_LAKE_BUCKET
        value: "{{ var.value.S3_DATA_LAKE_BUCKET }}"
      - name: MLFLOW_TRACKING_URI
        value: "{{ var.value.MLFLOW_TRACKING_URI }}"
